config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests, only: [:new, :create]

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  CAT_COLORS = %w(black white brown orange)
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: {in: CAT_COLORS, message:"Invalid color" }
  validates :sex, inclusion: { in: %w(M F), message: "Invalid sex" }

  def age
    current_date = Date.new(Time.now.year, Time.now.month, Time.now.day)
    ((current_date - birth_date) / 365).floor
  end

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED), message: "Invalid status" }
  validate :does_not_overlap_approved_requests

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest
      .where(cat_rental_requests: { cat_id: self.cat_id } )
      .where.not("end_date < ? OR start_date > ?", self.start_date, self.end_date)
      .where.not(id: self.id)
  end

  def overlapping_approved_requests
    overlapping_requests.where(cat_rental_requests: { status: "APPROVED" } )
  end

  def does_not_overlap_approved_requests
    if overlapping_approved_requests.exists?
      errors[:request] << "can't overlap with approved requests"
    end
  end

  def approve!
    request = CatRentalRequest.find_by(id: self.id)
    request.update_attributes(status: "APPROVED")

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat_id)
    else
      redirect_to new_cat_rental_request_url
    end
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = selected_cat
    @requests = CatRentalRequest.where(cat_id: @cat.id)
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = selected_cat
    render :edit
  end

  def update
    @cat = selected_cat
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render edit_cat_url(@post)
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      redirect_to new_cat_url
    end
  end


  private
    def selected_cat
      Cat.find_by(id: params[:id])
    end
    def cat_params
      params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h1> :D Cat request form </h1>

<form action="<%=cat_rental_requests_url%>" method="post">


<label for="cat_choice"></label>
<select id ="cat_choice" name="cat_rental_request[cat_id]">
  <% @cats.each do |cat| %>
    <option value="<%= cat.id %>"><%= cat.name %></option>
  <% end %>
</select>
<br>
<label for="start_date">Start Date</label>
  <input type="date" name="cat_rental_request[start_date]">
  <br>
<label for="end_date">End Date</label>
  <input type="date" name="cat_rental_request[end_date]">
<br>
<input type="Submit" value="Submit">

</form>

app/views/cats/_form.html.erb
<!-- <%# action == :edit ? action_url = cat_url(@cat) : action_url = cats_url %> -->
<% cat.persisted? ? action_url = cat_url(@cat) : action_url = cats_url %>

<form action="<%= action_url %>" method="POST">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="name">Name</label>
  <input type="text" name="cat[name]" id="name" value="<%=@cat.name%>">

  <br />

  <label>Sex
    <label>M
      <input <%= @cat.sex == "M" ? "checked" : "" %> type="radio" name="cat[sex]" value="M" id="sex1">
    </label>
    <label>F
      <input <%= @cat.sex == "F" ? "checked" : "" %> type="radio" name="cat[sex]" value="F" id="sex2">
    </label>
  </label>
  <br />

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= action == :edit ? "" : "selected" %> >Option</option>
    <% Cat::CAT_COLORS.each do |color| %>
    <option value="<%=color%>" <%= @cat.color == color ? "selected" : "" %>> <%= color.capitalize %></option>
    <% end %>
  </select>
  <br />
  <label for="date">Birth Date</label>
  <input type="date" name="cat[birth_date]" id="date" value="<%=@cat.birth_date%>">
  <br>
  <label for="description">Description</label>
  <textarea name="cat[description]"><%=@cat.description%></textarea>
  <br />
  <input type="submit" value="Submit">
</form>

app/views/cats/edit.html.erb
<h1>Edit a cat!</h1>

<!-- <form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <label for="name">Name</label>
  <input type="text" name="cat[name]" id="name" value="<%=@cat.name%>">
  <br />
  <label for="sex">Sex</label>
  <input <%= @cat.sex == "M" ? "checked" : "" %> type="radio" name="cat[sex]" value="M" id="sex1"><label for="sex1">M</label>
  <input <%= @cat.sex == "F" ? "checked" : "" %> type="radio" name="cat[sex]" value="F" id="sex2"><label for="sex2">F</label>
  <br />
  <label for="color">Color</label>

  <select name="cat[color]">
    <option disabled>Option</option>
    <% Cat::CAT_COLORS.each do |color| %>
    <option value="<%color%>" <%= @cat.color == color ? "selected": ""%>><%= color.capitalize %></option>
    <% end %>
  </select>
  <br />
  <label for="date">Birth Date</label>
  <input type="date" value="<%=@cat.birth_date%>" name="cat[birth_date]" id="date">
  <br>
  <label for="description">Description</label>
  <textarea name="cat[description]"><%=@cat.description%></textarea>
  <br />
  <input type="submit" value="Submit">
</form> -->

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>All Cats</h1>
  <ul>
    <% @cats.each do |cat| %>
    <li>
      <%= link_to cat.name, cat_url(cat) %>
    </li>
    <% end %>
  </ul>

app/views/cats/new.html.erb
<h1>Create a new cat!</h1>

<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Birth Date</th>
    <th>Sex</th>
    <th>Color</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<h2>Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
  </tr>
  <% @requests.each do |request| %>
    <tr>
      <td><%= request.start_date %></td>
      <td><%= request.end_date %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>